---

- name: Installing apache
  zypper: name=apache state=present
  become: yes
  become_method: sudo

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  - block:
    include_vars: "{{ item }}"
    with_first_found:
     - "{{ ansible_distribution }}.yml"
     - "{{ ansible_os_family }}.yml"
     - "default.yml"
