---

- name: install basic package
  action: >
    {{ ansible_pkg_mgr }} name=vim state=present update_cache=yes
  become: yes
  become_method: sudo
- name: install basic packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - httpd
  become: yes
  become_method: sudo
